server:
  port: 8080

spring:
  profiles:
    active: qa
---
spring:
  #profiles: dev
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Meh*Fir143
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: welcome to Daily code Buffer Dev!!

---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: Meh*Fir143
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: welcome to Daily code Buffer PROD!!

---
spring:
  config:
    activate:
      on-profile: "qa"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: Meh*Fir143
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: welcome to Daily code Buffer QA!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"